package com.orbclickthrough;

import com.google.inject.Provides;
import java.util.Arrays;
import java.util.Locale;
import java.util.Set;
import javax.inject.Inject;
import lombok.extern.slf4j.Slf4j;
import net.runelite.api.Client;
import net.runelite.api.GameState;
import net.runelite.api.MenuEntry;
import net.runelite.api.events.ClientTick;
import net.runelite.api.events.GameStateChanged;
import net.runelite.api.events.PostMenuSort;
import net.runelite.api.gameval.InterfaceID;
import net.runelite.api.widgets.Widget;
import net.runelite.client.callback.ClientThread;
import net.runelite.client.config.ConfigManager;
import net.runelite.client.eventbus.Subscribe;
import net.runelite.client.events.ConfigChanged;
import net.runelite.client.input.KeyManager;
import net.runelite.client.plugins.Plugin;
import net.runelite.client.plugins.PluginDescriptor;
import net.runelite.client.util.HotkeyListener;
import net.runelite.client.util.Text;

@Slf4j
@PluginDescriptor(
		name = "Orb Clickthrough",
		description = "Makes selected minimap orb buttons click-through with a configurable hotkey.",
		tags = {"orbs", "orb", "minimap", "clickthrough", "hotkey"}
)
public class OrbClickthroughPlugin extends Plugin
{
	private static final String CONFIG_GROUP = "orbclickthrough";

	// Expected menu entries generated by minimap orb widgets.
	// Menu entries are usually split into option + target, e.g. "Activate" + "Quick-prayers".
	private static final Set<String> HEALTH_MENU_OPTIONS = Set.of(
			"cure poison",
			"cure venom"
	);

	private static final Set<String> PRAYER_MENU_OPTIONS = Set.of(
			"activate",
			"deactivate"
	);

	private static final Set<String> PRAYER_MENU_TARGETS = Set.of(
			"quick-prayers"
	);

	private static final Set<String> RUN_MENU_OPTIONS = Set.of(
			"toggle run"
	);

	private static final Set<String> SPECIAL_ATTACK_MENU_OPTIONS = Set.of(
			"use special attack"
	);

	private static final Set<String> WORLD_MAP_MENU_OPTIONS = Set.of(
			"floating world map",
			"fullscreen world map",
			"minimise minimap"
	);

	private static final Set<String> XP_MENU_OPTIONS = Set.of(
			"setup",
			"hide",
			"show"
	);

	private static final Set<String> XP_MENU_TARGETS = Set.of(
			"xp drops"
	);

	private static final Set<String> ACTIVITY_MENU_OPTIONS = Set.of(
			"open activity adviser",
			"close activity adviser"
	);

	private static final Set<String> ACTIVITY_MENU_TARGETS = Set.of(
	);

	private static final Set<String> WIKI_MENU_OPTIONS = Set.of(
			"lookup",
			"search",
			"dps"
	);

	private static final Set<String> WIKI_MENU_TARGETS = Set.of(
			"wiki"
	);

	private static final Set<String> STORE_MENU_OPTIONS = Set.of(
			"open store",
			"bond pouch"
	);

	private static final Set<String> STORE_MENU_TARGETS = Set.of(
	);

	private static final Set<String> COMPASS_MENU_OPTIONS = Set.of(
			"look north",
			"look east",
			"look south",
			"look west"
	);

	private static final Set<String> LOGOUT_MENU_OPTIONS = Set.of(
			"logout",
			"world switcher"
	);

	private static final Set<String> LOGOUT_MENU_TARGETS = Set.of(
	);

	// Minimap orb widget component IDs
	private static final int ACTIVITY_BUTTON = InterfaceID.Orbs.CR_BUTTON;
	private static final int ACTIVITY_BACKING = InterfaceID.Orbs.CR_BACKING;

	private static final int XP_DROPS = InterfaceID.Orbs.XP_DROPS;

	private static final int HEALTH_BUTTON = InterfaceID.Orbs.HEALTHBUTTON;
	private static final int HEALTH_BACKING = InterfaceID.Orbs.HEALTH_BACKING;

	private static final int PRAYER_BUTTON = InterfaceID.Orbs.PRAYERBUTTON;
	private static final int PRAYER_BACKING = InterfaceID.Orbs.PRAYER_BACKING;

	private static final int RUN_BUTTON = InterfaceID.Orbs.RUNBUTTON;
	private static final int RUNENERGY_BACKING = InterfaceID.Orbs.RUNENERGY_BACKING;

	private static final int SPEC_BUTTON = InterfaceID.Orbs.SPECBUTTON;
	private static final int SPECENERGY_BACKING = InterfaceID.Orbs.SPECENERGY_BACKING;

	private static final int STORE_BUTTON = InterfaceID.Orbs.STORE_BUTTON;
	private static final int STORE_BACKING = InterfaceID.Orbs.STORE_BACKING;

	private static final int WORLDMAP = InterfaceID.Orbs.WORLDMAP;
	private static final int WORLDMAP_BACKING = InterfaceID.Orbs.WORLDMAP_BACKING;
	private static final int WORLDMAP_TOOLTIP = InterfaceID.Orbs.TOOLTIP;

	// Base game wiki orb
	private static final int WIKI_ICON = InterfaceID.Orbs.WIKI_ICON;

	// Wiki orb parent container.
	// Used to target the orb created by Wiki plugin, a dynamic replacement child.
	private static final int WIKI_CONTAINER = InterfaceID.Orbs.WIKI;

	// Compass/logout widgets.
	private static final int COMPASS_CLICK = InterfaceID.ToplevelPreEoc.COMPASSCLICK;
	private static final int COMPASS_NOCLICK_CHILD_INDEX = 0;
	private static final int COMPASS_ACTION_CHILD_INDEX = 1;

	private static final int LOGOUT_STONE = InterfaceID.ToplevelPreEoc.STONE10;

	// Radar noclick regions that cover the world map/wiki/logout/radar orb areas.
	// Resizable Modern
	private static final int MODERN_MAP_NOCLICK_0 = InterfaceID.ToplevelPreEoc.MAP_NOCLICK_0; // Radar/logout
	private static final int MODERN_MAP_NOCLICK_1 = InterfaceID.ToplevelPreEoc.MAP_NOCLICK_1;
	private static final int MODERN_MAP_NOCLICK_2 = InterfaceID.ToplevelPreEoc.MAP_NOCLICK_2;
	private static final int MODERN_MAP_NOCLICK_3 = InterfaceID.ToplevelPreEoc.MAP_NOCLICK_3;
	private static final int MODERN_MAP_NOCLICK_4 = InterfaceID.ToplevelPreEoc.MAP_NOCLICK_4;
	private static final int MODERN_MAP_NOCLICK_5 = InterfaceID.ToplevelPreEoc.MAP_NOCLICK_5;

	// Resizable Classic
	private static final int CLASSIC_MAP_NOCLICK_0 = InterfaceID.ToplevelOsrsStretch.MAP_NOCLICK_0; // Radar/logout
	private static final int CLASSIC_MAP_NOCLICK_1 = InterfaceID.ToplevelOsrsStretch.MAP_NOCLICK_1;
	private static final int CLASSIC_MAP_NOCLICK_2 = InterfaceID.ToplevelOsrsStretch.MAP_NOCLICK_2;
	private static final int CLASSIC_MAP_NOCLICK_3 = InterfaceID.ToplevelOsrsStretch.MAP_NOCLICK_3;
	private static final int CLASSIC_MAP_NOCLICK_4 = InterfaceID.ToplevelOsrsStretch.MAP_NOCLICK_4;
	private static final int CLASSIC_MAP_NOCLICK_5 = InterfaceID.ToplevelOsrsStretch.MAP_NOCLICK_5;

	@Inject
	private Client client;

	@Inject
	private ClientThread clientThread;

	@Inject
	private KeyManager keyManager;

	@Inject
	private OrbClickthroughConfig config;

	@Inject
	private OrbWidgetTransformer widgetTransformer;

	private HotkeyListener hotkeyListener;

	private boolean hotkeyHeld;
	private boolean toggleActive;

	@Override
	protected void startUp()
	{
		log.debug("Orb Clickthrough started");

		hotkeyListener = new HotkeyListener(() -> config.hotkey())
		{
			@Override
			public void hotkeyPressed()
			{
				if (config.activationMode() == OrbClickthroughActivationMode.TOGGLE_CLICK_THROUGH)
				{
					toggleActive = !toggleActive;
				}
				else
				{
					hotkeyHeld = true;
				}

				clientThread.invokeLater(OrbClickthroughPlugin.this::syncState);
			}

			@Override
			public void hotkeyReleased()
			{
				if (config.activationMode() != OrbClickthroughActivationMode.TOGGLE_CLICK_THROUGH)
				{
					hotkeyHeld = false;
					clientThread.invokeLater(OrbClickthroughPlugin.this::syncState);
				}
			}
		};

		keyManager.registerKeyListener(hotkeyListener);
		clientThread.invokeLater(this::syncState);
	}

	@Override
	protected void shutDown()
	{
		if (hotkeyListener != null)
		{
			keyManager.unregisterKeyListener(hotkeyListener);
			hotkeyListener = null;
		}

		clientThread.invokeLater(() ->
		{
			widgetTransformer.restoreEverythingChangedByUs();
			hotkeyHeld = false;
			toggleActive = false;
		});

		log.debug("Orb Clickthrough stopped");
	}

	@Subscribe
	public void onGameStateChanged(GameStateChanged event)
	{
		if (event.getGameState() != GameState.LOGGED_IN)
		{
			widgetTransformer.restoreEverythingChangedByUs();
			hotkeyHeld = false;
			toggleActive = false;
			return;
		}

		clientThread.invokeLater(this::syncState);
	}

	@Subscribe
	public void onConfigChanged(ConfigChanged event)
	{
		if (!CONFIG_GROUP.equals(event.getGroup()))
		{
			return;
		}

		clientThread.invokeLater(() ->
		{
			widgetTransformer.restoreEverythingChangedByUs();
			hotkeyHeld = false;
			toggleActive = false;
			syncState();
		});
	}

	@Subscribe
	public void onClientTick(ClientTick event)
	{
		syncState();
	}

	@Subscribe
	public void onPostMenuSort(PostMenuSort event)
	{
		if (!shouldApplyNow())
		{
			return;
		}

		MenuEntry[] entries = client.getMenu().getMenuEntries();

		MenuEntry[] filteredEntries = Arrays.stream(entries)
				.filter(entry -> !isBlockedOrbMenuEntry(entry))
				.toArray(MenuEntry[]::new);

		if (filteredEntries.length != entries.length)
		{
			client.getMenu().setMenuEntries(filteredEntries);
		}
	}

	private void syncState()
	{
		if (client.getGameState() != GameState.LOGGED_IN)
		{
			return;
		}

		// MAP_NOCLICK bounds are plugin-lifetime changes.
		// They are not tied to hotkey state or individual orb config options.
		syncNoClickRegions();

		if (shouldApplyNow())
		{
			applyConfiguredOrbChanges();
		}
		else
		{
			widgetTransformer.restoreOrbWidgetsChangedByUs();
		}
	}

	private boolean shouldApplyNow()
	{
		switch (config.activationMode())
		{
			case HOLD_TO_CLICK_THROUGH:
				return hotkeyHeld;
			case HOLD_TO_RESTORE_CLICKS:
				return !hotkeyHeld;
			case TOGGLE_CLICK_THROUGH:
				return toggleActive;
			default:
				return false;
		}
	}

	private void applyConfiguredOrbChanges()
	{
		if (config.hideWorldMapTooltip())
		{
			widgetTransformer.hideWidget(WORLDMAP_TOOLTIP);
		}

		if (config.manageHealthOrb())
		{
			widgetTransformer.allowClickThrough(HEALTH_BACKING);
			widgetTransformer.allowClickThrough(HEALTH_BUTTON);
		}

		if (config.managePrayerOrb())
		{
			widgetTransformer.allowClickThrough(PRAYER_BACKING);
			widgetTransformer.allowClickThrough(PRAYER_BUTTON);
		}

		if (config.manageRunOrb())
		{
			widgetTransformer.allowClickThrough(RUNENERGY_BACKING);
			widgetTransformer.allowClickThrough(RUN_BUTTON);
		}

		if (config.manageSpecialAttackOrb())
		{
			widgetTransformer.allowClickThrough(SPECENERGY_BACKING);
			widgetTransformer.allowClickThrough(SPEC_BUTTON);
		}

		if (config.manageWorldMapOrb())
		{
			widgetTransformer.allowClickThrough(WORLDMAP_BACKING);
			widgetTransformer.allowClickThrough(WORLDMAP);
		}

		if (config.manageXpOrb())
		{
			widgetTransformer.allowClickThrough(XP_DROPS);
		}

		if (config.manageActivityOrb())
		{
			widgetTransformer.allowClickThrough(ACTIVITY_BACKING);
			widgetTransformer.allowClickThrough(ACTIVITY_BUTTON);
		}

		if (config.manageWikiOrb())
		{
			widgetTransformer.allowClickThrough(WIKI_ICON);

			Widget wikiContainer = client.getWidget(WIKI_CONTAINER);

			if (wikiContainer != null)
			{
				widgetTransformer.allowClickThrough(wikiContainer);

				// The Wiki plugin adds its replacement orb as a dynamic child of WIKI_CONTAINER.
				Widget[] dynamicChildren = wikiContainer.getDynamicChildren();

				if (dynamicChildren != null)
				{
					for (Widget child : dynamicChildren)
					{
						if (child == null)
						{
							continue;
						}

						widgetTransformer.allowClickThrough(child);
					}
				}
			}
		}

		if (config.manageStoreOrb())
		{
			widgetTransformer.allowClickThrough(STORE_BACKING);
			widgetTransformer.allowClickThrough(STORE_BUTTON);
		}

		if (config.manageCompassOrb())
		{
			Widget compassClick = client.getWidget(COMPASS_CLICK);

			if (compassClick != null)
			{
				Widget compassNoClickChild = compassClick.getChild(COMPASS_NOCLICK_CHILD_INDEX);

				if (compassNoClickChild != null)
				{
					widgetTransformer.allowClickThrough(compassNoClickChild);
				}

				Widget compassActionChild = compassClick.getChild(COMPASS_ACTION_CHILD_INDEX);

				if (compassActionChild != null)
				{
					widgetTransformer.allowClickThrough(compassActionChild);
				}
			}
		}

		if (config.manageLogoutOrb())
		{
			widgetTransformer.allowClickThrough(LOGOUT_STONE);
		}
	}

	private void syncNoClickRegions()
	{
		if (!client.isResized())
		{
			widgetTransformer.restoreNoClickRegions(
					MODERN_MAP_NOCLICK_0,
					MODERN_MAP_NOCLICK_1,
					MODERN_MAP_NOCLICK_2,
					MODERN_MAP_NOCLICK_3,
					MODERN_MAP_NOCLICK_4,
					MODERN_MAP_NOCLICK_5,
					CLASSIC_MAP_NOCLICK_0,
					CLASSIC_MAP_NOCLICK_1,
					CLASSIC_MAP_NOCLICK_2,
					CLASSIC_MAP_NOCLICK_3,
					CLASSIC_MAP_NOCLICK_4,
					CLASSIC_MAP_NOCLICK_5
			);
			return;
		}

		widgetTransformer.updateNoClickRegions(
				MODERN_MAP_NOCLICK_1,
				MODERN_MAP_NOCLICK_2,
				MODERN_MAP_NOCLICK_3,
				MODERN_MAP_NOCLICK_4,
				MODERN_MAP_NOCLICK_5,
				CLASSIC_MAP_NOCLICK_1,
				CLASSIC_MAP_NOCLICK_2,
				CLASSIC_MAP_NOCLICK_3,
				CLASSIC_MAP_NOCLICK_4,
				CLASSIC_MAP_NOCLICK_5
		);

		widgetTransformer.patchCompassLogoutNoClickRegions(MODERN_MAP_NOCLICK_0);
		widgetTransformer.patchCompassLogoutNoClickRegions(CLASSIC_MAP_NOCLICK_0);
	}

	private boolean isBlockedOrbMenuEntry(MenuEntry entry)
	{
		String option = cleanMenuText(entry.getOption());
		String target = cleanMenuText(entry.getTarget());

		if (config.manageHealthOrb() && HEALTH_MENU_OPTIONS.contains(option))
		{
			return true;
		}

		if (config.managePrayerOrb() && PRAYER_MENU_OPTIONS.contains(option) && PRAYER_MENU_TARGETS.contains(target))
		{
			return true;
		}

		if (config.manageRunOrb() && RUN_MENU_OPTIONS.contains(option))
		{
			return true;
		}

		if (config.manageSpecialAttackOrb() && SPECIAL_ATTACK_MENU_OPTIONS.contains(option))
		{
			return true;
		}

		if (config.manageWorldMapOrb() && WORLD_MAP_MENU_OPTIONS.contains(option))
		{
			return true;
		}

		if (config.manageXpOrb() && (XP_MENU_OPTIONS.contains(option) || XP_MENU_TARGETS.contains(target)))
		{
			return true;
		}

		if (config.manageActivityOrb()
				&& (ACTIVITY_MENU_OPTIONS.contains(option) || ACTIVITY_MENU_TARGETS.contains(target)))
		{
			return true;
		}

		if (config.manageWikiOrb() && (WIKI_MENU_OPTIONS.contains(option) || WIKI_MENU_TARGETS.contains(target)))
		{
			return true;
		}

		if (config.manageStoreOrb() && (STORE_MENU_OPTIONS.contains(option) || STORE_MENU_TARGETS.contains(target)))
		{
			return true;
		}

		if (config.manageCompassOrb() && COMPASS_MENU_OPTIONS.contains(option))
		{
			return true;
		}

		return config.manageLogoutOrb()
				&& (LOGOUT_MENU_OPTIONS.contains(option) || LOGOUT_MENU_TARGETS.contains(target));
	}

	private String cleanMenuText(String text)
	{
		if (text == null)
		{
			return "";
		}

		return Text.removeTags(text).trim().toLowerCase(Locale.ROOT);
	}

	@Provides
	OrbClickthroughConfig provideConfig(ConfigManager configManager)
	{
		return configManager.getConfig(OrbClickthroughConfig.class);
	}
}