package com.orbclickthrough;

import com.google.inject.Provides;
import java.util.Arrays;
import java.util.Locale;
import java.util.Set;
import javax.inject.Inject;
import lombok.extern.slf4j.Slf4j;
import net.runelite.api.Client;
import net.runelite.api.GameState;
import net.runelite.api.MenuEntry;
import net.runelite.api.events.ClientTick;
import net.runelite.api.events.GameStateChanged;
import net.runelite.api.events.PostMenuSort;
import net.runelite.api.events.WidgetLoaded;
import net.runelite.api.gameval.InterfaceID;
import net.runelite.api.widgets.Widget;
import net.runelite.client.callback.ClientThread;
import net.runelite.client.config.ConfigManager;
import net.runelite.client.eventbus.Subscribe;
import net.runelite.client.events.ConfigChanged;
import net.runelite.client.input.KeyManager;
import net.runelite.client.plugins.Plugin;
import net.runelite.client.plugins.PluginDescriptor;
import net.runelite.client.util.HotkeyListener;
import net.runelite.client.util.Text;

@Slf4j
@PluginDescriptor(
		name = "Orb Clickthrough",
		description = "Makes selected minimap orb buttons click-through with a configurable hotkey.",
		tags = {"orbs", "orb", "minimap", "clickthrough", "hotkey"}
)
public class OrbClickthroughPlugin extends Plugin
{
	private static final String CONFIG_GROUP = "orbclickthrough";
	private static final int NO_ACTIVE_MAP_NOCLICK_0 = -1;

	// Expected menu entries generated by minimap orb widgets.
	// Menu entries are usually split into option + target, e.g. "Activate" + "Quick-prayers".
	private static final Set<String> HEALTH_MENU_OPTIONS = Set.of(
			"cure"
	);

	private static final Set<String> PRAYER_MENU_OPTIONS = Set.of(
			"activate",
			"deactivate"
	);

	private static final Set<String> PRAYER_MENU_TARGETS = Set.of(
			"quick-prayers"
	);

	private static final Set<String> RUN_MENU_OPTIONS = Set.of(
			"toggle run"
	);

	private static final Set<String> SPECIAL_ATTACK_MENU_OPTIONS = Set.of(
			"use"
	);

	private static final Set<String> SPECIAL_ATTACK_MENU_TARGETS = Set.of(
			"special attack"
	);

	private static final Set<String> WORLD_MAP_MENU_OPTIONS = Set.of(
			"floating world map",
			"fullscreen world map",
			"minimise minimap"
	);

	private static final Set<String> XP_MENU_OPTIONS = Set.of(
			"setup",
			"hide",
			"show"
	);

	private static final Set<String> XP_MENU_TARGETS = Set.of(
			"xp drops"
	);

	private static final Set<String> ACTIVITY_MENU_OPTIONS = Set.of(
			"open activity adviser",
			"close activity adviser"
	);

	private static final Set<String> WIKI_MENU_OPTIONS = Set.of(
			"lookup",
			"search",
			"dps"
	);

	private static final Set<String> WIKI_MENU_TARGETS = Set.of(
			"wiki"
	);

	private static final Set<String> STORE_MENU_OPTIONS = Set.of(
			"open store",
			"bond pouch"
	);

	private static final Set<String> COMPASS_MENU_OPTIONS = Set.of(
			"look north",
			"look east",
			"look south",
			"look west"
	);

	private static final Set<String> LOGOUT_MENU_OPTIONS = Set.of(
			"logout",
			"world switcher"
	);

	// Minimap orb widget component IDs
	private static final int ACTIVITY_BUTTON = InterfaceID.Orbs.CR_BUTTON;
	private static final int ACTIVITY_BACKING = InterfaceID.Orbs.CR_BACKING;

	private static final int XP_DROPS = InterfaceID.Orbs.XP_DROPS;

	private static final int HEALTH_CONTAINER = InterfaceID.Orbs.ORB_HEALTH;
	private static final int HEALTH_BUTTON = InterfaceID.Orbs.HEALTHBUTTON;
	private static final int HEALTH_BACKING = InterfaceID.Orbs.HEALTH_BACKING;

	private static final int PRAYER_CONTAINER = InterfaceID.Orbs.ORB_PRAYER;
	private static final int PRAYER_BUTTON = InterfaceID.Orbs.PRAYERBUTTON;
	private static final int PRAYER_BACKING = InterfaceID.Orbs.PRAYER_BACKING;

	private static final int RUN_CONTAINER = InterfaceID.Orbs.ORB_RUNENERGY;
	private static final int RUN_BUTTON = InterfaceID.Orbs.RUNBUTTON;
	private static final int RUNENERGY_BACKING = InterfaceID.Orbs.RUNENERGY_BACKING;

	private static final int SPEC_CONTAINER = InterfaceID.Orbs.ORB_SPECENERGY;
	private static final int SPEC_BUTTON = InterfaceID.Orbs.SPECBUTTON;
	private static final int SPECENERGY_BACKING = InterfaceID.Orbs.SPECENERGY_BACKING;

	private static final int STORE_CONTAINER = InterfaceID.Orbs.ORB_STORE;
	private static final int STORE_BUTTON = InterfaceID.Orbs.STORE_BUTTON;
	private static final int STORE_BACKING = InterfaceID.Orbs.STORE_BACKING;

	private static final int WORLDMAP = InterfaceID.Orbs.WORLDMAP;
	private static final int WORLDMAP_BACKING = InterfaceID.Orbs.WORLDMAP_BACKING;
	private static final int WORLDMAP_TOOLTIP = InterfaceID.Orbs.TOOLTIP;

	// Base game wiki orb
	private static final int WIKI_ICON = InterfaceID.Orbs.WIKI_ICON;

	// Wiki orb parent container.
	// Used to target the orb created by Wiki plugin, a dynamic replacement child.
	private static final int WIKI_CONTAINER = InterfaceID.Orbs.WIKI;

	// Compass/logout widgets.
	private static final int MODERN_COMPASS_CLICK = InterfaceID.ToplevelPreEoc.COMPASSCLICK;
	private static final int CLASSIC_COMPASS_CLICK = InterfaceID.ToplevelOsrsStretch.COMPASSCLICK;
	private static final int COMPASS_NOCLICK_CHILD_INDEX = 0;
	private static final int COMPASS_ACTION_CHILD_INDEX = 1;

	private static final int LOGOUT_STONE = InterfaceID.ToplevelPreEoc.STONE10;

	// Radar noclick regions that cover the world map/wiki/logout/radar orb areas.
	// Resizable Modern
	private static final int MODERN_MAP_NOCLICK_0 = InterfaceID.ToplevelPreEoc.MAP_NOCLICK_0; // Radar/logout
	private static final int MODERN_MAP_NOCLICK_1 = InterfaceID.ToplevelPreEoc.MAP_NOCLICK_1;
	private static final int MODERN_MAP_NOCLICK_2 = InterfaceID.ToplevelPreEoc.MAP_NOCLICK_2;
	private static final int MODERN_MAP_NOCLICK_3 = InterfaceID.ToplevelPreEoc.MAP_NOCLICK_3;
	private static final int MODERN_MAP_NOCLICK_4 = InterfaceID.ToplevelPreEoc.MAP_NOCLICK_4;
	private static final int MODERN_MAP_NOCLICK_5 = InterfaceID.ToplevelPreEoc.MAP_NOCLICK_5;

	// Resizable Classic
	private static final int CLASSIC_MAP_NOCLICK_0 = InterfaceID.ToplevelOsrsStretch.MAP_NOCLICK_0; // Radar/logout
	private static final int CLASSIC_MAP_NOCLICK_1 = InterfaceID.ToplevelOsrsStretch.MAP_NOCLICK_1;
	private static final int CLASSIC_MAP_NOCLICK_2 = InterfaceID.ToplevelOsrsStretch.MAP_NOCLICK_2;
	private static final int CLASSIC_MAP_NOCLICK_3 = InterfaceID.ToplevelOsrsStretch.MAP_NOCLICK_3;
	private static final int CLASSIC_MAP_NOCLICK_4 = InterfaceID.ToplevelOsrsStretch.MAP_NOCLICK_4;
	private static final int CLASSIC_MAP_NOCLICK_5 = InterfaceID.ToplevelOsrsStretch.MAP_NOCLICK_5;

	@Inject
	private Client client;

	@Inject
	private ClientThread clientThread;

	@Inject
	private KeyManager keyManager;

	@Inject
	private OrbClickthroughConfig config;

	@Inject
	private OrbWidgetTransformer widgetTransformer;

	private HotkeyListener hotkeyListener;

	private boolean hotkeyHeld;
	private boolean toggleActive;

	private boolean noClickRegionsSynced;
	private int noClickRegionsSyncedForMapNoClick0 = NO_ACTIVE_MAP_NOCLICK_0;
	private boolean orbWidgetsApplied;

	@Override
	protected void startUp()
	{
		log.debug("Orb Clickthrough started");

		hotkeyListener = new HotkeyListener(() -> config.hotkey())
		{
			@Override
			public void hotkeyPressed()
			{
				if (config.activationMode() == OrbClickthroughActivationMode.TOGGLE_CLICK_THROUGH)
				{
					toggleActive = !toggleActive;
				}
				else
				{
					hotkeyHeld = true;
				}

				clientThread.invokeLater(OrbClickthroughPlugin.this::syncState);
			}

			@Override
			public void hotkeyReleased()
			{
				if (config.activationMode() != OrbClickthroughActivationMode.TOGGLE_CLICK_THROUGH)
				{
					hotkeyHeld = false;
					clientThread.invokeLater(OrbClickthroughPlugin.this::syncState);
				}
			}
		};

		keyManager.registerKeyListener(hotkeyListener);
		markNoClickRegionsDirty();
		clientThread.invokeLater(this::syncState);
	}

	@Override
	protected void shutDown()
	{
		if (hotkeyListener != null)
		{
			keyManager.unregisterKeyListener(hotkeyListener);
			hotkeyListener = null;
		}

		clientThread.invokeLater(() ->
		{
			widgetTransformer.restoreEverythingChangedByUs();
			hotkeyHeld = false;
			toggleActive = false;
			orbWidgetsApplied = false;
			markNoClickRegionsDirty();
		});

		log.debug("Orb Clickthrough stopped");
	}

	@Subscribe
	public void onGameStateChanged(GameStateChanged event)
	{
		if (event.getGameState() != GameState.LOGGED_IN)
		{
			widgetTransformer.restoreEverythingChangedByUs();
			hotkeyHeld = false;
			toggleActive = false;
			orbWidgetsApplied = false;
			markNoClickRegionsDirty();
			return;
		}

		markNoClickRegionsDirty();
		clientThread.invokeLater(this::syncState);
	}

	@Subscribe
	public void onWidgetLoaded(WidgetLoaded event)
	{
		if (client.getGameState() != GameState.LOGGED_IN)
		{
			return;
		}

		/*
		 * Widgets can be recreated after login, layout changes, or other plugin changes.
		 * Resync on widget loads instead of doing the same work every client tick.
		 */
		markNoClickRegionsDirty();

		if (orbWidgetsApplied)
		{
			widgetTransformer.restoreOrbWidgetsChangedByUs();
			orbWidgetsApplied = false;
		}

		clientThread.invokeLater(this::syncState);
	}

	@Subscribe
	public void onConfigChanged(ConfigChanged event)
	{
		if (!CONFIG_GROUP.equals(event.getGroup()))
		{
			return;
		}

		clientThread.invokeLater(() ->
		{
			widgetTransformer.restoreEverythingChangedByUs();
			hotkeyHeld = false;
			toggleActive = false;
			orbWidgetsApplied = false;
			markNoClickRegionsDirty();
			syncState();
		});
	}

	@Subscribe
	public void onClientTick(ClientTick event)
	{
		// This is deliberately cheap and idempotent. It also repairs widget state
		// if another plugin or a client update recreates or resets an orb child.
		syncState();
		syncExtraNoClickRegionState();
	}

	@Subscribe
	public void onPostMenuSort(PostMenuSort event)
	{
		if (!shouldApplyNow())
		{
			return;
		}

		MenuEntry[] entries = client.getMenu().getMenuEntries();

		MenuEntry[] filteredEntries = Arrays.stream(entries)
				.filter(entry -> !isBlockedOrbMenuEntry(entry))
				.toArray(MenuEntry[]::new);

		if (filteredEntries.length != entries.length)
		{
			client.getMenu().setMenuEntries(filteredEntries);
		}
	}

	private void syncState()
	{
		if (client.getGameState() != GameState.LOGGED_IN)
		{
			return;
		}

		// MAP_NOCLICK bounds are plugin-lifetime changes.
		// They are not tied to hotkey state or individual orb config options.
		syncNoClickRegions();

		boolean shouldApply = shouldApplyNow();

		if (shouldApply)
		{
			applyConfiguredOrbChanges();
			orbWidgetsApplied = true;
		}
		else if (orbWidgetsApplied)
		{
			widgetTransformer.restoreOrbWidgetsChangedByUs();
			orbWidgetsApplied = false;
		}
	}

	private void syncExtraNoClickRegionState()
	{
		if (client.getGameState() != GameState.LOGGED_IN)
		{
			return;
		}

		int activeMapNoClick0 = getActiveMapNoClick0WidgetId();

		if (activeMapNoClick0 == MODERN_MAP_NOCLICK_0)
		{
			widgetTransformer.patchExtraNoClickRegion(MODERN_MAP_NOCLICK_0);
			widgetTransformer.restoreExtraNoClickRegion(CLASSIC_MAP_NOCLICK_0);
		}
		else if (activeMapNoClick0 == CLASSIC_MAP_NOCLICK_0)
		{
			widgetTransformer.patchExtraNoClickRegion(CLASSIC_MAP_NOCLICK_0);
			widgetTransformer.restoreExtraNoClickRegion(MODERN_MAP_NOCLICK_0);
		}
		else
		{
			widgetTransformer.restoreExtraNoClickRegion(MODERN_MAP_NOCLICK_0);
			widgetTransformer.restoreExtraNoClickRegion(CLASSIC_MAP_NOCLICK_0);
		}
	}

	private boolean shouldApplyNow()
	{
		switch (config.activationMode())
		{
			case HOLD_TO_CLICK_THROUGH:
				return hotkeyHeld;
			case HOLD_TO_RESTORE_CLICKS:
				return !hotkeyHeld;
			case TOGGLE_CLICK_THROUGH:
				return toggleActive;
			default:
				return false;
		}
	}

	private void applyConfiguredOrbChanges()
	{
		if (config.hideWorldMapTooltip())
		{
			widgetTransformer.hideWidget(WORLDMAP_TOOLTIP);
		}

		if (config.manageHealthOrb())
		{
			widgetTransformer.allowClickThroughTree(HEALTH_CONTAINER);
			widgetTransformer.allowClickThrough(HEALTH_BACKING);
		}

		if (config.managePrayerOrb())
		{
			widgetTransformer.allowClickThroughTree(PRAYER_CONTAINER);
			widgetTransformer.allowClickThrough(PRAYER_BACKING);
		}

		if (config.manageRunOrb())
		{
			widgetTransformer.allowClickThroughTree(RUN_CONTAINER);
			widgetTransformer.allowClickThrough(RUNENERGY_BACKING);
		}

		if (config.manageSpecialAttackOrb())
		{
			widgetTransformer.allowClickThroughTree(SPEC_CONTAINER);
			widgetTransformer.allowClickThrough(SPECENERGY_BACKING);
		}

		if (config.manageWorldMapOrb())
		{
			widgetTransformer.allowClickThroughTree(WORLDMAP_BACKING);
			widgetTransformer.allowClickThrough(WORLDMAP);
		}

		if (config.manageXpOrb())
		{
			widgetTransformer.allowClickThroughTree(XP_DROPS);
		}

		if (config.manageActivityOrb())
		{
			widgetTransformer.allowClickThroughTree(ACTIVITY_BACKING);
			widgetTransformer.allowClickThrough(ACTIVITY_BUTTON);
		}

		if (config.manageWikiOrb())
		{
			widgetTransformer.allowClickThroughTree(WIKI_ICON);

			Widget wikiContainer = client.getWidget(WIKI_CONTAINER);

			if (wikiContainer != null)
			{
				widgetTransformer.allowClickThroughTree(WIKI_CONTAINER);

				// The Wiki plugin adds its replacement orb as a dynamic child of WIKI_CONTAINER.
				Widget[] dynamicChildren = wikiContainer.getDynamicChildren();

				if (dynamicChildren != null)
				{
					for (Widget child : dynamicChildren)
					{
						if (child == null)
						{
							continue;
						}

						widgetTransformer.allowClickThrough(child);
					}
				}
			}
		}

		if (config.manageStoreOrb())
		{
			widgetTransformer.allowClickThroughTree(STORE_CONTAINER);
			widgetTransformer.allowClickThrough(STORE_BACKING);
		}

		if (config.manageCompassOrb())
		{
			Widget compassClick = getActiveCompassClickWidget();

			if (compassClick != null)
			{
				Widget compassNoClickChild = compassClick.getChild(COMPASS_NOCLICK_CHILD_INDEX);

				if (compassNoClickChild != null)
				{
					widgetTransformer.allowClickThrough(compassNoClickChild);
				}

				Widget compassActionChild = compassClick.getChild(COMPASS_ACTION_CHILD_INDEX);

				if (compassActionChild != null)
				{
					widgetTransformer.allowClickThrough(compassActionChild);
				}
			}
		}

		if (config.manageLogoutOrb())
		{
			widgetTransformer.allowClickThrough(LOGOUT_STONE);
		}
	}

	private void syncNoClickRegions()
	{
		int activeMapNoClick0 = getActiveMapNoClick0WidgetId();

		if (noClickRegionsSynced && noClickRegionsSyncedForMapNoClick0 == activeMapNoClick0)
		{
			return;
		}

		restoreAllNoClickRegions();
		noClickRegionsSyncedForMapNoClick0 = activeMapNoClick0;

		if (activeMapNoClick0 == NO_ACTIVE_MAP_NOCLICK_0)
		{
			noClickRegionsSynced = true;
			return;
		}

		if (activeMapNoClick0 == MODERN_MAP_NOCLICK_0)
		{
			widgetTransformer.updateNoClickRegions(
					MODERN_MAP_NOCLICK_1,
					MODERN_MAP_NOCLICK_2,
					MODERN_MAP_NOCLICK_3,
					MODERN_MAP_NOCLICK_4,
					MODERN_MAP_NOCLICK_5
			);
		}
		else
		{
			widgetTransformer.updateNoClickRegions(
					CLASSIC_MAP_NOCLICK_1,
					CLASSIC_MAP_NOCLICK_2,
					CLASSIC_MAP_NOCLICK_3,
					CLASSIC_MAP_NOCLICK_4,
					CLASSIC_MAP_NOCLICK_5
			);
		}

		widgetTransformer.patchExtraNoClickRegion(activeMapNoClick0);

		noClickRegionsSynced = true;
	}

	private void restoreAllNoClickRegions()
	{
		widgetTransformer.restoreNoClickRegions(
				MODERN_MAP_NOCLICK_0,
				MODERN_MAP_NOCLICK_1,
				MODERN_MAP_NOCLICK_2,
				MODERN_MAP_NOCLICK_3,
				MODERN_MAP_NOCLICK_4,
				MODERN_MAP_NOCLICK_5,
				CLASSIC_MAP_NOCLICK_0,
				CLASSIC_MAP_NOCLICK_1,
				CLASSIC_MAP_NOCLICK_2,
				CLASSIC_MAP_NOCLICK_3,
				CLASSIC_MAP_NOCLICK_4,
				CLASSIC_MAP_NOCLICK_5
		);
	}

	private int getActiveMapNoClick0WidgetId()
	{
		return selectActiveMapNoClick0(
				client.isResized(),
				isWidgetVisible(MODERN_MAP_NOCLICK_1),
				isWidgetVisible(CLASSIC_MAP_NOCLICK_1),
				client.getWidget(MODERN_MAP_NOCLICK_1) != null,
				client.getWidget(CLASSIC_MAP_NOCLICK_1) != null
		);
	}

	static int selectActiveMapNoClick0(
			boolean resized,
			boolean modernVisible,
			boolean classicVisible,
			boolean modernExists,
			boolean classicExists)
	{
		if (!resized)
		{
			return NO_ACTIVE_MAP_NOCLICK_0;
		}

		if (modernVisible)
		{
			return MODERN_MAP_NOCLICK_0;
		}

		if (classicVisible)
		{
			return CLASSIC_MAP_NOCLICK_0;
		}

		if (modernExists)
		{
			return MODERN_MAP_NOCLICK_0;
		}

		return classicExists ? CLASSIC_MAP_NOCLICK_0 : NO_ACTIVE_MAP_NOCLICK_0;
	}

	private Widget getActiveCompassClickWidget()
	{
		int activeMapNoClick0 = getActiveMapNoClick0WidgetId();

		if (activeMapNoClick0 == MODERN_MAP_NOCLICK_0)
		{
			return client.getWidget(MODERN_COMPASS_CLICK);
		}

		if (activeMapNoClick0 == CLASSIC_MAP_NOCLICK_0)
		{
			return client.getWidget(CLASSIC_COMPASS_CLICK);
		}

		Widget modernCompassClick = client.getWidget(MODERN_COMPASS_CLICK);
		return modernCompassClick != null ? modernCompassClick : client.getWidget(CLASSIC_COMPASS_CLICK);
	}

	private boolean isWidgetVisible(int widgetId)
	{
		Widget widget = client.getWidget(widgetId);
		return widget != null && !isHiddenOrAncestorHidden(widget);
	}

	private boolean isHiddenOrAncestorHidden(Widget widget)
	{
		Widget current = widget;

		while (current != null)
		{
			if (current.isHidden())
			{
				return true;
			}

			current = current.getParent();
		}

		return false;
	}

	private void markNoClickRegionsDirty()
	{
		noClickRegionsSynced = false;
		noClickRegionsSyncedForMapNoClick0 = NO_ACTIVE_MAP_NOCLICK_0;
	}

	private boolean isBlockedOrbMenuEntry(MenuEntry entry)
	{
		String option = cleanMenuText(entry.getOption());
		String target = cleanMenuText(entry.getTarget());
		int widgetId = entry.getParam1();

		if (config.manageHealthOrb()
				&& isWidgetOrChildOfAny(widgetId, HEALTH_CONTAINER, HEALTH_BUTTON, HEALTH_BACKING)
				&& HEALTH_MENU_OPTIONS.contains(option))
		{
			return true;
		}

		if (config.managePrayerOrb()
				&& isWidgetOrChildOfAny(widgetId, PRAYER_CONTAINER, PRAYER_BUTTON, PRAYER_BACKING)
				&& (PRAYER_MENU_OPTIONS.contains(option) || PRAYER_MENU_TARGETS.contains(target)))
		{
			return true;
		}

		if (config.manageRunOrb()
				&& isWidgetOrChildOfAny(widgetId, RUN_CONTAINER, RUN_BUTTON, RUNENERGY_BACKING)
				&& RUN_MENU_OPTIONS.contains(option))
		{
			return true;
		}

		if (config.manageSpecialAttackOrb()
				&& isWidgetOrChildOfAny(widgetId, SPEC_CONTAINER, SPEC_BUTTON, SPECENERGY_BACKING)
				&& (SPECIAL_ATTACK_MENU_OPTIONS.contains(option) || SPECIAL_ATTACK_MENU_TARGETS.contains(target)))
		{
			return true;
		}

		if (config.manageWorldMapOrb()
				&& isWidgetOrChildOfAny(widgetId, WORLDMAP, WORLDMAP_BACKING)
				&& WORLD_MAP_MENU_OPTIONS.contains(option))
		{
			return true;
		}

		if (config.manageXpOrb()
				&& isWidgetOrChildOfAny(widgetId, XP_DROPS)
				&& (XP_MENU_OPTIONS.contains(option) || XP_MENU_TARGETS.contains(target)))
		{
			return true;
		}

		if (config.manageActivityOrb()
				&& isWidgetOrChildOfAny(widgetId, ACTIVITY_BUTTON, ACTIVITY_BACKING)
				&& ACTIVITY_MENU_OPTIONS.contains(option))
		{
			return true;
		}

		if (config.manageWikiOrb()
				&& isWidgetOrChildOfAny(widgetId, WIKI_ICON, WIKI_CONTAINER)
				&& (WIKI_MENU_OPTIONS.contains(option) || WIKI_MENU_TARGETS.contains(target)))
		{
			return true;
		}

		if (config.manageStoreOrb()
				&& isWidgetOrChildOfAny(widgetId, STORE_CONTAINER, STORE_BUTTON, STORE_BACKING)
				&& STORE_MENU_OPTIONS.contains(option))
		{
			return true;
		}

		if (config.manageCompassOrb()
				&& isWidgetOrChildOfAny(widgetId, MODERN_COMPASS_CLICK, CLASSIC_COMPASS_CLICK)
				&& COMPASS_MENU_OPTIONS.contains(option))
		{
			return true;
		}

		return config.manageLogoutOrb()
				&& isWidgetOrChildOfAny(widgetId, LOGOUT_STONE)
				&& LOGOUT_MENU_OPTIONS.contains(option);
	}

	private boolean isWidgetOrChildOfAny(int widgetId, int... expectedWidgetIds)
	{
		Widget widget = client.getWidget(widgetId);

		while (widget != null)
		{
			for (int expectedWidgetId : expectedWidgetIds)
			{
				if (widget.getId() == expectedWidgetId)
				{
					return true;
				}
			}

			widget = widget.getParent();
		}

		return false;
	}

	private String cleanMenuText(String text)
	{
		if (text == null)
		{
			return "";
		}

		return Text.removeTags(text).trim().toLowerCase(Locale.ROOT);
	}

	@Provides
	OrbClickthroughConfig provideConfig(ConfigManager configManager)
	{
		return configManager.getConfig(OrbClickthroughConfig.class);
	}
}